DROP TABLE IF EXISTS MODEL;
CREATE TABLE MODEL (
  MODEL_ID SERIAL NOT NULL,
  MODEL_NAME char(64) DEFAULT NULL,
  MODEL_NUM_CLASSES int DEFAULT NULL,
  MODEL_LAST_RETRAIN date DEFAULT NULL,
  MODEL_SIZE int DEFAULT NULL,
  PRIMARY KEY (MODEL_ID)
);

DROP TABLE IF EXISTS PACKET;
CREATE TABLE PACKET (
  PACK_ID SERIAL NOT NULL,
  PACK_ORIGIN_IP char(64) DEFAULT NULL,
  PACK_DEST_IP char(64) DEFAULT NULL,
  PACK_PAYLOAD text DEFAULT NULL,
  PRIMARY KEY (PACK_ID)
);

DROP TABLE IF EXISTS CLASS;
CREATE TABLE CLASS (
  CLASS_NAME varchar(64) NOT NULL UNIQUE,
  MODEL_ID int NOT NULL,
  PRIMARY KEY (CLASS_NAME, MODEL_ID),
  FOREIGN KEY (MODEL_ID) REFERENCES MODEL (MODEL_ID)
);

DROP TABLE IF EXISTS PACK_LABEL;
CREATE TABLE PACK_LABEL (
  PACK_ID int NOT NULL,
  MODEL_ID int NOT NULL,
  PACK_CLASS varchar(64) NOT NULL,
  PACK_CONFIDENCE float NOT NULL,
  PRIMARY KEY (PACK_ID,MODEL_ID),
  FOREIGN KEY (PACK_ID) REFERENCES PACKET (PACK_ID),
  FOREIGN KEY (MODEL_ID) REFERENCES MODEL (MODEL_ID),
  FOREIGN KEY (PACK_CLASS) REFERENCES CLASS (CLASS_NAME)
);
