DROP TABLE IF EXISTS MODEL CASCADE;
CREATE TABLE MODEL (
  MODEL_ID SERIAL NOT NULL,
  MODEL_NAME char(64) DEFAULT NULL,
  MODEL_NUM_CLASSES int DEFAULT NULL,
  MODEL_LAST_RETRAIN date DEFAULT NULL,
  MODEL_SIZE int DEFAULT NULL,
  PRIMARY KEY (MODEL_ID)
);

DROP TABLE IF EXISTS PACKET CASCADE;
CREATE TABLE PACKET (
  PACK_ID SERIAL NOT NULL,
  PACK_ORIGIN_IP char(64) DEFAULT NULL,
  PACK_DEST_IP char(64) DEFAULT NULL,
  PACK_PAYLOAD text DEFAULT NULL,
  PROTOCOL CHAR(16) DEFAULT NULL,
  LENGTH INT NOT NULL,
  T_DELTA float DEFAULT NULL,
  TTL INT DEFAULT NULL,
  TIME TIMESTAMP DEFAULT NULL,
  SRCPORT INT DEFAULT NULL,
  DESTPORT INT DEFAULT NULL,
  PRIMARY KEY (PACK_ID)
);

DROP TABLE IF EXISTS CLASS CASCADE;
CREATE TABLE CLASS (
  CLASS_NAME varchar(64) NOT NULL UNIQUE,
  MODEL_ID int NOT NULL,
  PRIMARY KEY (CLASS_NAME, MODEL_ID),
  FOREIGN KEY (MODEL_ID) REFERENCES MODEL (MODEL_ID)
);

DROP TABLE IF EXISTS PACK_LABEL CASCADE;
CREATE TABLE PACK_LABEL (
  PACK_ID int NOT NULL,
  MODEL_ID int NOT NULL,
  PACK_CLASS varchar(64) NOT NULL,
  PACK_CONFIDENCE float NOT NULL,
  PRIMARY KEY (PACK_ID,MODEL_ID),
  FOREIGN KEY (PACK_ID) REFERENCES PACKET (PACK_ID),
  FOREIGN KEY (MODEL_ID) REFERENCES MODEL (MODEL_ID),
  FOREIGN KEY (PACK_CLASS) REFERENCES CLASS (CLASS_NAME)
);

DROP TABLE IF EXISTS PACK_TAG CASCADE;
CREATE TABLE PACK_TAG (
  ID SERIAL PRIMARY KEY,
  PACK_ID int NOT NULL,
  TAGS JSONB NOT NULL,
  FOREIGN KEY (PACK_ID) REFERENCES PACKET (PACK_ID)
);

INSERT INTO model(model_id) VALUES (1);
INSERT INTO class (class_name, model_id) VALUES ('BENIGN', 1),('Infiltration', 1), ('Bot', 1), ('PortScan', 1), ('DDoS', 1), ('FTP-Patator', 1), ('SSH-Patator', 1), ('DoS slowloris', 1), ('DoS Slowhttptest', 1), ('DoS Hulk', 1), ('DoS GoldenEye', 1), ('Heartbleed', 1), ('Web Attack – Brute Force', 1), ('Web Attack – XSS', 1), ('Web Attack – Sql Injection', 1);